name: build-push

on:
  push:
    branches:
      - 'main'

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        run: |
          # Build the backend image
          docker build -t dimoy/backend:latest ./backend
          
          # Tag the image with current date and time
          DATE_TIME_TAG=$(date +"%Y%m%d%H%M%S")
          docker tag dimoy/backend:latest dimoy/backend:$DATE_TIME_TAG
          
          # Push the images
          docker push dimoy/backend:latest
          docker push dimoy/backend:$DATE_TIME_TAG
          
        env:
          DOCKER_BUILDKIT: 1

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        run: |
          # Build the frontend image
          docker build -t dimoy/frontend:latest ./frontend
          
          # Tag the image with current date and time
          DATE_TIME_TAG=$(date +"%Y%m%d%H%M%S")
          docker tag dimoy/frontend:latest dimoy/frontend:$DATE_TIME_TAG
          
          # Push the images
          docker push dimoy/frontend:latest
          docker push dimoy/frontend:$DATE_TIME_TAG
          
        env:
          DOCKER_BUILDKIT: 1
